# Furina — pneuma
foreground #F5F7FA
background #3854A9
selection_foreground #3854A9
selection_background #E8F5FE
cursor #E8F5FE
cursor_text_color #3854A9
url_color #82B1FF
active_tab_foreground #3854A9
active_tab_background #E8F5FE
inactive_tab_foreground #C0D0E0
inactive_tab_background #4D5B99
tab_bar_background #183B75
active_border_color #82B1FF
inactive_border_color #4D5B99
bell_border_color #FF8A80
color0 #183B75
color1 #FF5252
color2 #69F0AE
color3 #FFD740
color4 #82B1FF
color5 #B388FF
color6 #40C4FF
color7 #E8F5FE
color8 #4D5B99
color9 #FF8A80
color10 #B2FF59
color11 #FFE57F
color12 #AEC4FF
color13 #D1C4E9
color14 #84FFFF
color15 #FFFFFF
mark1_foreground #3854A9
mark1_background #82B1FF
mark2_foreground #3854A9
mark2_background #B388FF
mark3_foreground #3854A9
mark3_background #40C4FF
