# Furina — pneuma
set -g fish_color_normal F5F7FA
set -g fish_color_command 82B1FF
set -g fish_color_keyword B388FF
set -g fish_color_quote 84FFFF
set -g fish_color_redirection B388FF
set -g fish_color_end AEC4FF
set -g fish_color_error FF5252
set -g fish_color_param F5F7FA
set -g fish_color_comment AEC4FF
set -g fish_color_selection --background=4D5B99
set -g fish_color_operator B388FF
set -g fish_color_escape 84FFFF
set -g fish_color_autosuggestion AEC4FF
set -g fish_color_cwd 82B1FF
set -g fish_color_user 84FFFF
set -g fish_color_host B388FF
set -g fish_color_cancel FF5252
set -g fish_color_status FF5252
set -g fish_pager_color_progress 82B1FF
set -g fish_pager_color_prefix B388FF
set -g fish_pager_color_completion F5F7FA
set -g fish_pager_color_description AEC4FF
